name: Python CI

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13  

    - name: Print User Information
      run: |
        echo "Full Name: Maksim Gorlo"  
        echo "Group Number: M3112"  
        echo "GitHub Username: $GITHUB_ACTOR"  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run tests
      run: |
        pytest 

    - name: Lint code with black
      run: |
        pip install black
        black --check
